[
    "Systematic Review of Evidence",
    "Public Policies",
    "Solutions",
    "Incentives",
    "Recycling",
    "Audience",
    "Coordination",
    "Modernization",
    "Innovation",
    "Action Plan",
    "Digital District",
    "Digital Agenda",
    "Information and Communication Technologies",
    "Environmental and Social Analysis",
    "Mitigation of Environmental Impacts",
    "Cleaning",
    "Maintenance",
    "Pollutants",
    "Psychosocial factors",
    "Ergonomics",
    "Protected Area",
    "Biodiversity",
    "Environmental Protection Zones",
    "Zero Extinction Alliance",
    "Bird Conservation",
    "Connectivity",
    "Healthcare institutions",
    "Security institutions",
    "Public spaces",
    "Municipalities",
    "Cloud Computing",
    "Data Centers",
    "Innovation",
    "Education",
    "Healthcare",
    "Government digitalization",
    "Beneficiaries",
    "Impact indicators",
    "SMART outcome indicators",
    "Industry of ICTs",
    "Digitalization",
    "Capacity building",
    "Legal framework",
    "Public services",
    "Citizen satisfaction",
    "Predictive algorithm",
    "Services and countries",
    "Service selection",
    "Online survey",
    "SOC-Py",
    "SIEM",
    "Logs",
    "Monitoring",
    "Incident management",
    "Technological Park",
    "Road connections",
    "Site characteristics",
    "Legal framework",
    "Average cost",
    "Data cleaning and coding",
    "Information verification",
    "Data consistency",
    "Economic activity coding",
    "Record validation",
    "Geotechnical study",
    "Groundwater",
    "Soil classification",
    "Penetration tests",
    "Foundation costs",
    "ITD",
    "Value chain",
    "Sectors",
    "Minimum requirements",
    "Sequencing",
    "Consumer companies",
    "Producing companies",
    "Research",
    "Sampling design",
    "Field work",
    "Environmental and social impacts",
    "Impact identification matrix",
    "Importance of impacts matrix",
    "Stakeholder consultation",
    "Resources for implementing the consultation process",
    "Data center",
    "Technical documents",
    "Maintenance plan",
    "Alarms",
    "Current infrastructure",
    "Public institutions",
    "Fiber optics",
    "Digital services",
    "Capacity demand",
    "Strategic Planning",
    "National Development Plan 2030",
    "ICTs Master Plan",
    "Digital Divide",
    "ICTs in SENATICs",
    "Loan",
    "Digital Agenda Support Program",
    "Paraguay",
    "Financing",
    "Executive Directors",
    "ICTs (Information and Communication Technologies)",
    "Competitiveness",
    "Public Services",
    "Procurement policies",
    "Procurement methods",
    "Thresholds for procurement methods",
    "Estimated times by procurement method",
    "Expenditure category",
    "Safeguard Policy",
    "Environmental Impact",
    "High Risk Rating",
    "Disaster Risk Management",
    "Monitoring",
    "Evaluation",
    "Indicators",
    "Implementation",
    "Electronic Government",
    "Inclusion and Appropriation",
    "Enablers (security, standard policies, access and infrastructure, capacity building, and legal framework)",
    "Authorization",
    "Improvement Project",
    "National Secretariat of Information and Communication Technologies (SENATICS)",
    "Public credit",
    "Public debt",
    "Liquidity", 
    "Fiscal responsibility",
    "Monetary effects", 
    "State financial management",
    "Public investment projects",
    "Recommendations of the Control Body",
    "Financing through international loans",
    "Improvement of competitiveness with laws in Paraguay",
    "Loan",
    "Competitiveness",
    "ICT",
    "Paraguay", 
    "Ministry of Finance", 
    "Electronic Government",
    "Procedures",
    "Simplification",
Digitalization
SENATICS (National Secretariat of Information and Communication Technologies"

"Administrative costs
Methodology
Procedures
Citizens
Opportunity costs"

"Cyber Security
Critical Infrastructure
Capacity Building
National Cyber Security Strategy
Regulation"

"Targeting
Promotion of the digital agenda
Digital development
Priority sectors
Technological agendas"

"Public policies
Science, Technology, and Innovation
National Development Plan
Information infrastructure
National Innovation System"